version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: mergeimage:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
    working_dir: /workdir
    command: python main.py
